## 절대 모멘텀

In [82]:
import pandas as pd
import numpy as np
from datetime import datetime

df = pd.read_csv("../../data/csv/AAPL.csv", index_col="Date")
df.head()

                Open      High       Low     Close  Adj Close       Volume
Date
1980-12-12  0.513393  0.515625  0.513393  0.513393   0.410525  117258400.0
1980-12-15  0.488839  0.488839  0.486607  0.486607   0.389106   43971200.0
1980-12-16  0.453125  0.453125  0.450893  0.450893   0.360548   26432000.0
1980-12-17  0.462054  0.464286  0.462054  0.462054   0.369472   21610400.0
1980-12-18  0.475446  0.477679  0.475446  0.475446   0.380182   18362400.0

In [83]:
df.index = pd.to_datetime(df.index, utc = False)

In [84]:
# series - strftime
df.index.strftime("%Y-%m")

Index(['1980-12', '1980-12', '1980-12', '1980-12', '1980-12', '1980-12',
       '1980-12', '1980-12', '1980-12', '1980-12',
       ...
       '2019-06', '2019-06', '2019-06', '2019-06', '2019-06', '2019-06',
       '2019-06', '2019-06', '2019-06', '2019-06'],
      dtype='object', name='Date', length=9715)

In [85]:
df['STD-YM'] = df.index.strftime("%Y-%m")

In [86]:
# df.loc['1980-12-30']
# 전날과 다음날의 STD-YM 값이 다르면 달이 바뀌는 날인 것이다
flag = df['STD-YM'].shift(-1) != df['STD-YM']
df2 = df.loc[flag]
df2

,Open,High,Low,Close,Adj Close,Volume,STD-YM
Date,,,,,,,
1980-12-31,0.611607,0.611607,0.609375,0.609375,0.487276,8937600.0,1980-12
1981-01-30,0.508929,0.508929,0.504464,0.504464,0.403385,11547200.0,1981-01
1981-02-27,0.473214,0.477679,0.473214,0.473214,0.378397,3690400.0,1981-02
1981-03-31,0.441964,0.441964,0.437500,0.437500,0.349839,3998400.0,1981-03
1981-04-30,0.506696,0.511161,0.506696,0.506696,0.405170,3152800.0,1981-04
...,...,...,...,...,...,...,...
2019-02-28,174.320007,174.910004,172.919998,173.149994,172.485748,28215400.0,2019-02
2019-03-29,189.830002,190.080002,188.539993,189.949997,189.221313,23564000.0,2019-03
2019-04-30,203.059998,203.399994,199.110001,200.669998,199.900192,46534900.0,2019-04
2019-05-31,176.229996,177.990005,174.990005,175.070007,175.070007,27043600.0,2019-05
2019-06-24,198.539993,200.160004,198.169998,199.169998,199.169998,9025362.0,2019-06

In [87]:
# 월말의 데이터를 출력하는 방법
# case1
df.loc['1981-1'].tail(1)
test_df = pd.DataFrame()
for year in range(1980, 2026): # 년도를 반복
    for month in range(1, 13): # 월월을 반복복
        try:
            idx = f"{year}-{month}"
            df2 = df.loc[idx].tail(1)
            test_df = pd.concat([test_df, df2], axis=0)
        except Exception as e:
            print(e)
            continue

'1980-1'
'1980-2'
'1980-3'
'1980-4'
'1980-5'
'1980-6'
'1980-7'
'1980-8'
'1980-9'
'1980-10'
'1980-11'
'2019-7'
'2019-8'
'2019-9'
'2019-10'
'2019-11'
'2019-12'
'2020-1'
'2020-2'
'2020-3'
'2020-4'
'2020-5'
'2020-6'
'2020-7'
'2020-8'
'2020-9'
'2020-10'
'2020-11'
'2020-12'
'2021-1'
'2021-2'
'2021-3'
'2021-4'
'2021-5'
'2021-6'
'2021-7'
'2021-8'
'2021-9'
'2021-10'
'2021-11'
'2021-12'
'2022-1'
'2022-2'
'2022-3'
'2022-4'
'2022-5'
'2022-6'
'2022-7'
'2022-8'
'2022-9'
'2022-10'
'2022-11'
'2022-12'
'2023-1'
'2023-2'
'2023-3'
'2023-4'
'2023-5'
'2023-6'
'2023-7'
'2023-8'
'2023-9'
'2023-10'
'2023-11'
'2023-12'
'2024-1'
'2024-2'
'2024-3'
'2024-4'
'2024-5'
'2024-6'
'2024-7'
'2024-8'
'2024-9'
'2024-10'
'2024-11'
'2024-12'
'2025-1'
'2025-2'
'2025-3'
'2025-4'
'2025-5'
'2025-6'
'2025-7'
'2025-8'
'2025-9'
'2025-10'
'2025-11'
'2025-12'

In [88]:
test_df

,Open,High,Low,Close,Adj Close,Volume,STD-YM
Date,,,,,,,
1980-12-31,0.611607,0.611607,0.609375,0.609375,0.487276,8937600.0,1980-12
1981-01-30,0.508929,0.508929,0.504464,0.504464,0.403385,11547200.0,1981-01
1981-02-27,0.473214,0.477679,0.473214,0.473214,0.378397,3690400.0,1981-02
1981-03-31,0.441964,0.441964,0.437500,0.437500,0.349839,3998400.0,1981-03
1981-04-30,0.506696,0.511161,0.506696,0.506696,0.405170,3152800.0,1981-04
...,...,...,...,...,...,...,...
2019-02-28,174.320007,174.910004,172.919998,173.149994,172.485748,28215400.0,2019-02
2019-03-29,189.830002,190.080002,188.539993,189.949997,189.221313,23564000.0,2019-03
2019-04-30,203.059998,203.399994,199.110001,200.669998,199.900192,46534900.0,2019-04
2019-05-31,176.229996,177.990005,174.990005,175.070007,175.070007,27043600.0,2019-05
2019-06-24,198.539993,200.160004,198.169998,199.169998,199.169998,9025362.0,2019-06

In [89]:
# case2
# STD-YM 이용 : 현재의 STD-YM 데이터와 다음 인덱스의 STD-YM이 다른 경우 
flag = df['STD-YM'] != df.shift(-1)['STD-YM']
df.loc[flag]

,Open,High,Low,Close,Adj Close,Volume,STD-YM
Date,,,,,,,
1980-12-31,0.611607,0.611607,0.609375,0.609375,0.487276,8937600.0,1980-12
1981-01-30,0.508929,0.508929,0.504464,0.504464,0.403385,11547200.0,1981-01
1981-02-27,0.473214,0.477679,0.473214,0.473214,0.378397,3690400.0,1981-02
1981-03-31,0.441964,0.441964,0.437500,0.437500,0.349839,3998400.0,1981-03
1981-04-30,0.506696,0.511161,0.506696,0.506696,0.405170,3152800.0,1981-04
...,...,...,...,...,...,...,...
2019-02-28,174.320007,174.910004,172.919998,173.149994,172.485748,28215400.0,2019-02
2019-03-29,189.830002,190.080002,188.539993,189.949997,189.221313,23564000.0,2019-03
2019-04-30,203.059998,203.399994,199.110001,200.669998,199.900192,46534900.0,2019-04
2019-05-31,176.229996,177.990005,174.990005,175.070007,175.070007,27043600.0,2019-05
2019-06-24,198.539993,200.160004,198.169998,199.169998,199.169998,9025362.0,2019-06

In [90]:
# case3
# unique() 함수를 이용

ym_list = df['STD-YM'].unique()
# 빈데이터프레임 생성
month_last_df = pd.DataFrame()
for ym in ym_list:
    data = df.loc[ym].tail(1)
    month_last_df = pd.concat([month_last_df, data], axis=0)

In [91]:
# month_last_df에서
# 전월의 수정 종가 데이터를 BF_1M에 대입
# 전년도의 수정종가 데이터를 BF_12M에 대입

month_last_df['BF_1M'] = month_last_df['Adj Close'].shift(1)
month_last_df['BF_12M'] = month_last_df['Adj Close'].shift(12)

In [92]:
month_last_df.head(30)

,Open,High,Low,Close,Adj Close,Volume,STD-YM,BF_1M,BF_12M
Date,,,,,,,,,
1980-12-31,0.611607,0.611607,0.609375,0.609375,0.487276,8937600.0,1980-12,NaN,NaN
1981-01-30,0.508929,0.508929,0.504464,0.504464,0.403385,11547200.0,1981-01,0.487276,NaN
1981-02-27,0.473214,0.477679,0.473214,0.473214,0.378397,3690400.0,1981-02,0.403385,NaN
1981-03-31,0.441964,0.441964,0.437500,0.437500,0.349839,3998400.0,1981-03,0.378397,NaN
1981-04-30,0.506696,0.511161,0.506696,0.506696,0.405170,3152800.0,1981-04,0.349839,NaN
1981-05-29,0.591518,0.593750,0.591518,0.591518,0.472996,14845600.0,1981-05,0.405170,NaN
1981-06-30,0.466518,0.466518,0.464286,0.464286,0.371257,8976800.0,1981-06,0.472996,NaN
1981-07-31,0.446429,0.448661,0.446429,0.446429,0.356978,2738400.0,1981-07,0.371257,NaN
1981-08-31,0.359375,0.361607,0.359375,0.359375,0.287367,10236800.0,1981-08,0.356978,NaN
1981-09-30,0.272321,0.274554,0.272321,0.272321,0.217757,12499200.0,1981-09,0.287367,NaN
1981-10-30,0.357143,0.359375,0.357143,0.357143,0.285583,13182400.0,1981-10,0.217757,NaN
1981-11-30,0.334821,0.334821,0.332589,0.332589,0.265949,5992000.0,1981-11,0.285583,NaN
1981-12-31,0.395089,0.397321,0.395089,0.395089,0.315926,13664000.0,1981-12,0.265949,0.487276
1982-01-29,0.363839,0.366071,0.363839,0.363839,0.290937,13288800.0,1982-01,0.315926,0.403385
1982-02-26,0.325893,0.328125,0.325893,0.325893,0.260594,4356800.0,1982-02,0.290937,0.378397
1982-03-31,0.301339,0.303571,0.301339,0.301339,0.240960,12538400.0,1982-03,0.260594,0.349839
1982-04-30,0.263393,0.265625,0.263393,0.263393,0.210617,69350400.0,1982-04,0.240960,0.405170
1982-05-28,0.250000,0.252232,0.250000,0.250000,0.199908,4799200.0,1982-05,0.210617,0.472996
1982-06-30,0.227679,0.229911,0.227679,0.227679,0.182059,16906400.0,1982-06,0.199908,0.371257
1982-07-30,0.241071,0.243304,0.241071,0.241071,0.192768,9654400.0,1982-07,0.182059,0.356978
1982-08-31,0.321429,0.323661,0.321429,0.321429,0.257024,35140000.0,1982-08,0.192768,0.287367
1982-09-30,0.328125,0.328125,0.325893,0.325893,0.260594,18670400.0,1982-09,0.257024,0.217757
1982-10-29,0.448661,0.453125,0.441964,0.453125,0.362333,29528800.0,1982-10,0.260594,0.285583
1982-11-30,0.515625,0.571429,0.513393,0.569196,0.455147,39799200.0,1982-11,0.362333,0.265949
1982-12-31,0.535714,0.542411,0.533482,0.533482,0.426589,12415200.0,1982-12,0.455147,0.315926
1983-01-31,0.732143,0.743304,0.716518,0.729911,0.583660,47000800.0,1983-01,0.426589,0.290937
1983-02-28,0.834821,0.837054,0.812500,0.814732,0.651485,33073600.0,1983-02,0.583660,0.260594
1983-03-31,0.790179,0.794643,0.754464,0.754464,0.603293,21285600.0,1983-03,0.651485,0.240960
1983-04-29,0.892857,0.906250,0.881696,0.901786,0.721096,77078400.0,1983-04,0.603293,0.210617
1983-05-31,1.058036,1.058036,1.011161,1.031250,0.824620,11384800.0,1983-05,0.721096,0.199908

### 거래 내역 생성
- 전월의 수정종가가 전년도의 수정종가 보다 높을 때 매수한다
- 모멘텀 인덱스 : (전월의 수정종가 / 전년도의 수정종가) - 1
- 모멘텀 인덱스가 0보다는 크고 무한대가 아닌 경우 -> 매수

In [93]:
# 거래내역은 df에 생성
df['trade'] = ''
for idx in month_last_df.index:
    signal = ''
    momentum_index = month_last_df.loc[idx, 'BF_1M'] / month_last_df.loc[idx, 'BF_12M'] - 1
    flag = (momentum_index > 0) & (momentum_index != np.inf)
    if flag:
        signal = 'buy'
    
    print(f"날짜 : {idx}, 모멘텀 인덱스 : {momentum_index}, signal : {signal}")
    df.loc[idx:, 'trade'] = signal

날짜 : 1980-12-31 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-01-30 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-02-27 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-03-31 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-04-30 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-05-29 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-06-30 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-07-31 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-08-31 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-09-30 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-10-30 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-11-30 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1981-12-31 00:00:00, 모멘텀 인덱스 : -0.45421280752591964, signal :
날짜 : 1982-01-29 00:00:00, 모멘텀 인덱스 : -0.21681272233722126, signal :
날짜 : 1982-02-26 00:00:00, 모멘텀 인덱스 : -0.23113291067318187, signal :
날짜 : 1982-03-31 00:00:00, 모멘텀 인덱스 : -0.2551030616940936, signal :
날짜 : 1982-04-30 00:00:00, 모멘텀 인덱스 : -0.4052866697929264, signal :
날짜 : 1982-05-28 00:00:00, 모멘텀 인덱스 : -0.554717164627185, signal :
날짜 : 1982-06-30 00:00:00, 모멘텀 인덱스 : -0.4615374255569592, signal :
날짜 : 1982-07-30 00:00:00, 모멘텀 인덱스 : -0.4899993837155231, signal :
날짜 : 1982-08-31 00:00:00, 모멘텀 인덱스 : -0.32919228721460714, signal :
날짜 : 1982-09-30 00:00:00, 모멘텀 인덱스 : 0.18032485752467187, signal : buy
날짜 : 1982-10-29 00:00:00, 모멘텀 인덱스 : -0.0875017070343822, signal :
날짜 : 1982-11-30 00:00:00, 모멘텀 인덱스 : 0.36241535031152594, signal : buy
날짜 : 1982-12-31 00:00:00, 모멘텀 인덱스 : 0.44067598108417805, signal : buy
날짜 : 1983-01-31 00:00:00, 모멘텀 인덱스 : 0.46625901827543426, signal : buy
날짜 : 1983-02-28 00:00:00, 모멘텀 인덱스 : 1.2397292339808281, signal : buy
날짜 : 1983-03-31 00:00:00, 모멘텀 인덱스 : 1.7037060092961487, signal : buy
날짜 : 1983-04-29 00:00:00, 모멘텀 인덱스 : 1.8644079062943635, signal : buy
날짜 : 1983-05-31 00:00:00, 모멘텀 인덱스 : 2.6071392840706724, signal : buy
날짜 : 1983-06-30 00:00:00, 모멘텀 인덱스 : 3.529410795401491, signal : buy
날짜 : 1983-07-29 00:00:00, 모멘텀 인덱스 : 2.620372675962815, signal : buy
날짜 : 1983-08-31 00:00:00, 모멘텀 인덱스 : 0.9375038906872513, signal : buy
날짜 : 1983-09-30 00:00:00, 모멘텀 인덱스 : 1.0410984136242583, signal : buy
날짜 : 1983-10-31 00:00:00, 모멘텀 인덱스 : -0.08866981478363822, signal :
날짜 : 1983-11-30 00:00:00, 모멘텀 인덱스 : -0.2901963541449246, signal :
날짜 : 1983-12-30 00:00:00, 모멘텀 인덱스 : -0.3179922595284923, signal :
날짜 : 1984-01-31 00:00:00, 모멘텀 인덱스 : -0.4036699448308947, signal :
날짜 : 1984-02-29 00:00:00, 모멘텀 인덱스 : -0.4575347091644474, signal :
날짜 : 1984-03-30 00:00:00, 모멘텀 인덱스 : -0.3786982444682765, signal :
날짜 : 1984-04-30 00:00:00, 모멘텀 인덱스 : -0.5099015942398792, signal :
날짜 : 1984-05-31 00:00:00, 모멘텀 인덱스 : -0.4567097572215081, signal :
날짜 : 1984-06-29 00:00:00, 모멘텀 인덱스 : -0.3989772056421337, signal :
날짜 : 1984-07-31 00:00:00, 모멘텀 인덱스 : -0.24014377943110743, signal :
날짜 : 1984-08-31 00:00:00, 모멘텀 인덱스 : -0.31543641826064395, signal :
날짜 : 1984-09-28 00:00:00, 모멘텀 인덱스 : 0.1459457003982374, signal : buy
날짜 : 1984-10-31 00:00:00, 모멘텀 인덱스 : 0.11049788742203592, signal : buy
날짜 : 1984-11-30 00:00:00, 모멘텀 인덱스 : 0.2208588113577854, signal : buy
날짜 : 1984-12-31 00:00:00, 모멘텀 인덱스 : 0.01538267050515163, signal : buy
날짜 : 1985-01-31 00:00:00, 모멘텀 인덱스 : 0.1767701919594351, signal : buy
날짜 : 1985-02-28 00:00:00, 모멘텀 인덱스 : 0.10476299732943462, signal : buy
날짜 : 1985-03-29 00:00:00, 모멘텀 인덱스 : 0.0, signal :
날짜 : 1985-04-30 00:00:00, 모멘텀 인덱스 : -0.29482062820306787, signal :
날짜 : 1985-05-31 00:00:00, 모멘텀 인덱스 : -0.2765962012068214, signal :
날짜 : 1985-06-28 00:00:00, 모멘텀 인덱스 : -0.3443394107247151, signal :
날짜 : 1985-07-31 00:00:00, 모멘텀 인덱스 : -0.29411893946467915, signal :
날짜 : 1985-08-30 00:00:00, 모멘텀 인덱스 : -0.40094398211402305, signal :
날짜 : 1985-09-30 00:00:00, 모멘텀 인덱스 : -0.40298470020598565, signal :
날짜 : 1985-10-31 00:00:00, 모멘텀 인덱스 : -0.36683436892055865, signal :
날짜 : 1985-11-29 00:00:00, 모멘텀 인덱스 : -0.24747317547989867, signal :
날짜 : 1985-12-31 00:00:00, 모멘텀 인덱스 : -0.3090146196018083, signal :
날짜 : 1986-01-31 00:00:00, 모멘텀 인덱스 : -0.24137939361740657, signal :
날짜 : 1986-02-28 00:00:00, 모멘텀 인덱스 : -0.06565499366171668, signal :
날짜 : 1986-03-31 00:00:00, 모멘텀 인덱스 : 0.12994182181903358, signal : buy
날짜 : 1986-04-30 00:00:00, 모멘텀 인덱스 : 0.32941261769562113, signal : buy
날짜 : 1986-05-30 00:00:00, 모멘텀 인덱스 : 0.7410076582023379, signal : buy
날짜 : 1986-06-30 00:00:00, 모멘텀 인덱스 : 1.0555590139442232, signal : buy
날짜 : 1986-07-31 00:00:00, 모멘텀 인덱스 : 1.2598453333098059, signal : buy
날짜 : 1986-08-29 00:00:00, 모멘텀 인덱스 : 1.083333722401453, signal : buy
날짜 : 1986-09-30 00:00:00, 모멘텀 인덱스 : 1.3492103016505408, signal : buy
날짜 : 1986-10-31 00:00:00, 모멘텀 인덱스 : 0.7986568853426785, signal : buy
날짜 : 1986-11-28 00:00:00, 모멘텀 인덱스 : 0.7205002662101077, signal : buy
날짜 : 1986-12-31 00:00:00, 모멘텀 인덱스 : 0.818180371234573, signal : buy
날짜 : 1987-01-30 00:00:00, 모멘텀 인덱스 : 0.7513514332005873, signal : buy
날짜 : 1987-02-27 00:00:00, 모멘텀 인덱스 : 1.2199995517931073, signal : buy
날짜 : 1987-03-31 00:00:00, 모멘텀 인덱스 : 1.477878453586524, signal : buy
날짜 : 1987-04-30 00:00:00, 모멘텀 인덱스 : 1.1322301039023577, signal : buy
날짜 : 1987-05-29 00:00:00, 모멘텀 인덱스 : 1.1418910222437577, signal : buy
날짜 : 1987-06-30 00:00:00, 모멘텀 인덱스 : 1.2054350881576683, signal : buy
날짜 : 1987-07-31 00:00:00, 모멘텀 인덱스 : 1.5959374572803284, signal : buy
날짜 : 1987-08-31 00:00:00, 모멘텀 인덱스 : 1.2331165488105875, signal : buy
날짜 : 1987-09-30 00:00:00, 모멘텀 인덱스 : 2.232944009733438, signal : buy
날짜 : 1987-10-30 00:00:00, 모멘텀 인덱스 : 2.272712195220614, signal : buy
날짜 : 1987-11-30 00:00:00, 모멘텀 인덱스 : 0.9366820445930686, signal : buy
날짜 : 1987-12-31 00:00:00, 모멘텀 인덱스 : 0.6377793724764615, signal : buy
날짜 : 1988-01-29 00:00:00, 모멘텀 인덱스 : 0.5210847820353797, signal : buy
날짜 : 1988-02-29 00:00:00, 모멘텀 인덱스 : 0.19164434804444852, signal : buy
날짜 : 1988-03-31 00:00:00, 모멘텀 인덱스 : 0.34264780608987566, signal : buy
날짜 : 1988-04-29 00:00:00, 모멘텀 인덱스 : 0.016516130400549445, signal : buy
날짜 : 1988-05-31 00:00:00, 모멘텀 인덱스 : 0.04364093417657666, signal : buy
날짜 : 1988-06-30 00:00:00, 모멘텀 인덱스 : 0.03232567916731077, signal : buy
날짜 : 1988-07-29 00:00:00, 모멘텀 인덱스 : 0.1295657465812523, signal : buy
날짜 : 1988-08-31 00:00:00, 모멘텀 인덱스 : -0.17318468627504224, signal :
날짜 : 1988-09-30 00:00:00, 모멘텀 인덱스 : -0.28856519895827026, signal :
날짜 : 1988-10-31 00:00:00, 모멘텀 인덱스 : 0.1287565598260656, signal : buy
날짜 : 1988-11-30 00:00:00, 모멘텀 인덱스 : 0.17730822183931338, signal : buy
날짜 : 1988-12-30 00:00:00, 모멘텀 인덱스 : -0.09654517912872074, signal :
날짜 : 1989-01-31 00:00:00, 모멘텀 인덱스 : -0.021868112954886, signal :
날짜 : 1989-02-28 00:00:00, 모멘텀 인덱스 : -0.11636815614628693, signal :
날짜 : 1989-03-31 00:00:00, 모멘텀 인덱스 : -0.08532735929674684, signal :
날짜 : 1989-04-28 00:00:00, 모멘텀 인덱스 : -0.12302163825865986, signal :
날짜 : 1989-05-31 00:00:00, 모멘텀 인덱스 : -0.05338213699143346, signal :
날짜 : 1989-06-30 00:00:00, 모멘텀 인덱스 : 0.04224488662711745, signal : buy
날짜 : 1989-07-31 00:00:00, 모멘텀 인덱스 : -0.061588153176580174, signal :
날짜 : 1989-08-31 00:00:00, 모멘텀 인덱스 : 0.004443355684758954, signal : buy
날짜 : 1989-09-29 00:00:00, 모멘텀 인덱스 : 0.0391817656862814, signal : buy
날짜 : 1989-10-31 00:00:00, 모멘텀 인덱스 : 0.16361469359350211, signal : buy
날짜 : 1989-11-30 00:00:00, 모멘텀 인덱스 : 0.24494566904117843, signal : buy
날짜 : 1989-12-29 00:00:00, 모멘텀 인덱스 : 0.11017228474706608, signal : buy
날짜 : 1990-01-31 00:00:00, 모멘텀 인덱스 : -0.05705761495765016, signal :
날짜 : 1990-02-28 00:00:00, 모멘텀 인덱스 : -0.05546315287247727, signal :
날짜 : 1990-03-30 00:00:00, 모멘텀 인덱스 : -0.03579531497517463, signal :
날짜 : 1990-04-30 00:00:00, 모멘텀 인덱스 : 0.042669594876927563, signal : buy
날짜 : 1990-05-31 00:00:00, 모멘텀 인덱스 : -0.16872872991063237, signal :
날짜 : 1990-06-29 00:00:00, 모멘텀 인덱스 : 0.010880028002216768, signal : buy
날짜 : 1990-07-31 00:00:00, 모멘텀 인덱스 : 0.1380349952260369, signal : buy
날짜 : 1990-08-31 00:00:00, 모멘텀 인덱스 : -0.04816907422122163, signal :
날짜 : 1990-09-28 00:00:00, 모멘텀 인덱스 : -0.15894638435221842, signal :
날짜 : 1990-10-31 00:00:00, 모멘텀 인덱스 : -0.3691485940694542, signal :
날짜 : 1990-11-30 00:00:00, 모멘텀 인덱스 : -0.2987960451645426, signal :
날짜 : 1990-12-31 00:00:00, 모멘텀 인덱스 : 0.05550988558134762, signal : buy
날짜 : 1991-01-31 00:00:00, 모멘텀 인덱스 : 0.28042406837579326, signal : buy
날짜 : 1991-02-28 00:00:00, 모멘텀 인덱스 : 0.6473317586170582, signal : buy
날짜 : 1991-03-28 00:00:00, 모멘텀 인덱스 : 0.4384356905745934, signal : buy
날짜 : 1991-04-30 00:00:00, 모멘텀 인덱스 : 0.7465027454920234, signal : buy
날짜 : 1991-05-31 00:00:00, 모멘텀 인덱스 : 0.344670063316185, signal : buy
날짜 : 1991-06-28 00:00:00, 모멘텀 인덱스 : 0.06192291382635773, signal : buy
날짜 : 1991-07-31 00:00:00, 모멘텀 인덱스 : -0.0009497875730861693, signal :
날짜 : 1991-08-30 00:00:00, 모멘텀 인덱스 : 0.2600473939729382, signal : buy
날짜 : 1991-09-30 00:00:00, 모멘텀 인덱스 : 0.8464421752641682, signal : buy
날짜 : 1991-10-31 00:00:00, 모멘텀 인덱스 : 0.6263655809645623, signal : buy
날짜 : 1991-11-29 00:00:00, 모멘텀 인덱스 : 0.4110955713527773, signal : buy
날짜 : 1991-12-31 00:00:00, 모멘텀 인덱스 : 0.19129296307705834, signal : buy
날짜 : 1992-01-31 00:00:00, 모멘텀 인덱스 : 0.025284370779798726, signal : buy
날짜 : 1992-02-28 00:00:00, 모멘텀 인덱스 : 0.13920332392089785, signal : buy
날짜 : 1992-03-31 00:00:00, 모멘텀 인덱스 : 0.0017153083959857707, signal : buy
날짜 : 1992-04-30 00:00:00, 모멘텀 인덱스 : 0.06876570708956486, signal : buy
날짜 : 1992-05-29 00:00:00, 모멘텀 인덱스 : 0.2876429211921614, signal : buy
날짜 : 1992-06-30 00:00:00, 모멘텀 인덱스 : 0.44919843739869014, signal : buy
날짜 : 1992-07-31 00:00:00, 모멘텀 인덱스 : 0.04674698304512814, signal : buy
날짜 : 1992-08-31 00:00:00, 모멘텀 인덱스 : -0.11235982802616329, signal :
날짜 : 1992-09-30 00:00:00, 모멘텀 인덱스 : -0.062326781539996934, signal :
날짜 : 1992-10-30 00:00:00, 모멘텀 인덱스 : -0.11588589435903385, signal :
날짜 : 1992-11-30 00:00:00, 모멘텀 인덱스 : 0.04130269291103805, signal : buy
날짜 : 1992-12-31 00:00:00, 모멘텀 인덱스 : 0.028867675223065214, signal : buy
날짜 : 1993-01-29 00:00:00, 모멘텀 인덱스 : -0.06915717855504944, signal :
날짜 : 1993-02-26 00:00:00, 모멘텀 인덱스 : -0.11247887382512733, signal :
날짜 : 1993-03-31 00:00:00, 모멘텀 인덱스 : -0.08189411366517707, signal :
날짜 : 1993-04-30 00:00:00, 모멘텀 인덱스 : -0.13569928783494933, signal :
날짜 : 1993-05-28 00:00:00, 모멘텀 인덱스 : -0.13449629462680335, signal :
날짜 : 1993-06-30 00:00:00, 모멘텀 인덱스 : 0.19045855675718482, signal : buy
날짜 : 1993-07-30 00:00:00, 모멘텀 인덱스 : -0.1473657479104532, signal :
날짜 : 1993-08-31 00:00:00, 모멘텀 인덱스 : -0.3928657933038002, signal :
날짜 : 1993-09-30 00:00:00, 모멘텀 인덱스 : -0.4063664297564884, signal :
날짜 : 1993-10-29 00:00:00, 모멘텀 인덱스 : -0.5499275585882191, signal :
날짜 : 1993-11-30 00:00:00, 모멘텀 인덱스 : -0.46056070407772187, signal :
날짜 : 1993-12-31 00:00:00, 모멘텀 인덱스 : -0.46629869729510853, signal :
날짜 : 1994-01-31 00:00:00, 모멘텀 인덱스 : -0.5023382444647975, signal :
날짜 : 1994-02-28 00:00:00, 모멘텀 인덱스 : -0.37581454518870827, signal :
날짜 : 1994-03-31 00:00:00, 모멘텀 인덱스 : -0.2815049211066799, signal :
날짜 : 1994-04-29 00:00:00, 모멘텀 인덱스 : -0.3422879071898288, signal :
날짜 : 1994-05-31 00:00:00, 모멘텀 인덱스 : -0.4640272381829461, signal :
날짜 : 1994-06-30 00:00:00, 모멘텀 인덱스 : -0.24790487194138922, signal :
날짜 : 1994-07-29 00:00:00, 모멘텀 인덱스 : -0.030100617231757942, signal :
날짜 : 1994-08-31 00:00:00, 모멘텀 인덱스 : 0.2854551504421263, signal : buy
날짜 : 1994-09-30 00:00:00, 모멘텀 인덱스 : 0.5708856536800069, signal : buy
날짜 : 1994-10-31 00:00:00, 모멘텀 인덱스 : 0.11163302296816369, signal : buy
날짜 : 1994-11-30 00:00:00, 모멘텀 인덱스 : 0.38619789579731867, signal : buy
날짜 : 1994-12-30 00:00:00, 모멘텀 인덱스 : 0.2914704771426362, signal : buy
날짜 : 1995-01-31 00:00:00, 모멘텀 인덱스 : 0.2076394915948172, signal : buy
날짜 : 1995-02-28 00:00:00, 모멘텀 인덱스 : 0.11774640021694016, signal : buy
날짜 : 1995-03-31 00:00:00, 모멘텀 인덱스 : 0.20371403757658157, signal : buy
날짜 : 1995-04-28 00:00:00, 모멘텀 인덱스 : 0.19057315241997563, signal : buy
날짜 : 1995-05-31 00:00:00, 모멘텀 인덱스 : 0.3198043514776536, signal : buy
날짜 : 1995-06-30 00:00:00, 모멘텀 인덱스 : 0.5873194006686795, signal : buy
날짜 : 1995-07-31 00:00:00, 모멘텀 인덱스 : 0.39511020062028, signal : buy
날짜 : 1995-08-31 00:00:00, 모멘텀 인덱스 : 0.2541757352618341, signal : buy
날짜 : 1995-09-29 00:00:00, 모멘텀 인덱스 : 0.2908925529150186, signal : buy
날짜 : 1995-10-31 00:00:00, 모멘텀 인덱스 : -0.12771554898855997, signal :
날짜 : 1995-11-30 00:00:00, 모멘텀 인덱스 : -0.01708990773775676, signal :
날짜 : 1995-12-29 00:00:00, 모멘텀 인덱스 : -0.011260021618180294, signal :
날짜 : 1996-01-31 00:00:00, 모멘텀 인덱스 : -0.20150065176103593, signal :
날짜 : 1996-02-29 00:00:00, 모멘텀 인덱스 : -0.29458008426228066, signal :
날짜 : 1996-03-29 00:00:00, 모멘텀 인덱스 : -0.21310596810850602, signal :
날짜 : 1996-04-30 00:00:00, 모멘텀 인덱스 : -0.35228538918622787, signal :
날짜 : 1996-05-31 00:00:00, 모멘텀 인덱스 : -0.4100959329444034, signal :
날짜 : 1996-06-28 00:00:00, 모멘텀 인덱스 : -0.43411782787736464, signal :
날짜 : 1996-07-31 00:00:00, 모멘텀 인덱스 : -0.5305976499233049, signal :
날짜 : 1996-08-30 00:00:00, 모멘텀 인덱스 : -0.4867758716978826, signal :
날짜 : 1996-09-30 00:00:00, 모멘텀 인덱스 : -0.3469621029998958, signal :
날짜 : 1996-10-31 00:00:00, 모멘텀 인덱스 : -0.3870782037618967, signal :
날짜 : 1996-11-29 00:00:00, 모멘텀 인덱스 : -0.39672185297214646, signal :
날짜 : 1996-12-31 00:00:00, 모멘텀 인덱스 : -0.24313697963931347, signal :
날짜 : 1997-01-31 00:00:00, 모멘텀 인덱스 : -0.24434337310365895, signal :
날짜 : 1997-02-28 00:00:00, 모멘텀 인덱스 : -0.39545506319256707, signal :
날짜 : 1997-03-31 00:00:00, 모멘텀 인덱스 : -0.3384221600794294, signal :
날짜 : 1997-04-30 00:00:00, 모멘텀 인덱스 : -0.25128275735462846, signal :
날짜 : 1997-05-30 00:00:00, 모멘텀 인덱스 : -0.34928251324068627, signal :
날짜 : 1997-06-30 00:00:00, 모멘텀 인덱스 : -0.2083339675079373, signal :
날짜 : 1997-07-31 00:00:00, 모멘텀 인덱스 : -0.3522734702001571, signal :
날짜 : 1997-08-29 00:00:00, 모멘텀 인덱스 : -0.278350977456294, signal :
날짜 : 1997-09-30 00:00:00, 모멘텀 인덱스 : -0.019718370727842438, signal :
날짜 : 1997-10-31 00:00:00, 모멘텀 인덱스 : -0.05706543263919284, signal :
날짜 : 1997-11-28 00:00:00, 모멘텀 인덱스 : -0.29404353246519255, signal :
날짜 : 1997-12-31 00:00:00, 모멘텀 인덱스 : -0.1497004337700637, signal :
날짜 : 1998-01-30 00:00:00, 모멘텀 인덱스 : -0.21052520273309983, signal :
날짜 : 1998-02-27 00:00:00, 모멘텀 인덱스 : 0.12692315257371, signal : buy
날짜 : 1998-03-31 00:00:00, 모멘텀 인덱스 : 0.29452015208859095, signal : buy
날짜 : 1998-04-30 00:00:00, 모멘텀 인덱스 : 0.6176470035252644, signal : buy
날짜 : 1998-05-29 00:00:00, 모멘텀 인덱스 : 0.6466176544097573, signal : buy
날짜 : 1998-06-30 00:00:00, 모멘텀 인덱스 : 0.8684224692487821, signal : buy
날짜 : 1998-07-31 00:00:00, 모멘텀 인덱스 : 0.6392867449106696, signal : buy
날짜 : 1998-08-31 00:00:00, 모멘텀 인덱스 : 0.5919539976516819, signal : buy
날짜 : 1998-09-30 00:00:00, 모멘텀 인덱스 : 0.43804188754824747, signal : buy
날짜 : 1998-10-30 00:00:00, 모멘텀 인덱스 : 1.238539479141449, signal : buy
날짜 : 1998-11-30 00:00:00, 모멘텀 인덱스 : 1.0915493211366014, signal : buy
날짜 : 1998-12-31 00:00:00, 모멘텀 인덱스 : 1.4333319533702356, signal : buy
날짜 : 1999-01-29 00:00:00, 모멘텀 인덱스 : 1.2354945290859933, signal : buy
날짜 : 1999-02-26 00:00:00, 모멘텀 인덱스 : 0.7433873278594711, signal : buy
날짜 : 1999-03-31 00:00:00, 모멘텀 인덱스 : 0.2659085573219462, signal : buy
날짜 : 1999-04-30 00:00:00, 모멘텀 인덱스 : 0.3127855454041275, signal : buy
날짜 : 1999-05-28 00:00:00, 모멘텀 인덱스 : 0.7276995474244008, signal : buy
날짜 : 1999-06-30 00:00:00, 모멘텀 인덱스 : 0.5359466273888933, signal : buy
날짜 : 1999-07-30 00:00:00, 모멘텀 인덱스 : 0.3375451396837821, signal : buy
날짜 : 1999-08-31 00:00:00, 모멘텀 인덱스 : 0.7855703680018367, signal : buy
날짜 : 1999-09-30 00:00:00, 모멘텀 인덱스 : 0.7114741014480115, signal : buy
날짜 : 1999-10-29 00:00:00, 모멘텀 인덱스 : 0.7053871604559883, signal : buy
날짜 : 1999-11-30 00:00:00, 모멘텀 인덱스 : 1.508805359374953, signal : buy
날짜 : 1999-12-31 00:00:00, 모멘텀 인덱스 : 1.3908387088714727, signal : buy
날짜 : 2000-01-31 00:00:00, 모멘텀 인덱스 : 1.4962056396634233, signal : buy
날짜 : 2000-02-29 00:00:00, 모멘텀 인덱스 : 1.980251016829329, signal : buy
날짜 : 2000-03-31 00:00:00, 모멘텀 인덱스 : 2.1895642707725584, signal : buy
날짜 : 2000-04-28 00:00:00, 모멘텀 인덱스 : 1.952444811008407, signal : buy
날짜 : 2000-05-31 00:00:00, 모멘텀 인덱스 : 1.8156048432726042, signal : buy
날짜 : 2000-06-30 00:00:00, 모멘텀 인덱스 : 0.8137653833625034, signal : buy
날짜 : 2000-07-31 00:00:00, 모멘텀 인덱스 : 0.881032967701536, signal : buy
날짜 : 2000-08-31 00:00:00, 모멘텀 인덱스 : 0.557471613453117, signal : buy
날짜 : 2000-09-29 00:00:00, 모멘텀 인덱스 : 0.9249748718096287, signal : buy
날짜 : 2000-10-31 00:00:00, 모멘텀 인덱스 : -0.357254180643365, signal :
날짜 : 2000-11-30 00:00:00, 모멘텀 인덱스 : -0.600255503330785, signal :
날짜 : 2000-12-29 00:00:00, 모멘텀 인덱스 : -0.679027179677853, signal :
날짜 : 2001-01-31 00:00:00, 모멘텀 인덱스 : -0.7132529266789895, signal :
날짜 : 2001-02-28 00:00:00, 모멘텀 인덱스 : -0.622682673013883, signal :
날짜 : 2001-03-30 00:00:00, 모멘텀 인덱스 : -0.7312472288457972, signal :
날짜 : 2001-04-30 00:00:00, 모멘텀 인덱스 : -0.644211768912852, signal :
날짜 : 2001-05-31 00:00:00, 모멘텀 인덱스 : -0.3930952844805805, signal :
날짜 : 2001-06-29 00:00:00, 모멘텀 인덱스 : -0.6190929817580877, signal :
날짜 : 2001-07-31 00:00:00, 모멘텀 인덱스 : -0.5424353895372755, signal :
날짜 : 2001-08-31 00:00:00, 모멘텀 인덱스 : -0.6916513268956561, signal :
날짜 : 2001-09-28 00:00:00, 모멘텀 인덱스 : -0.279611461283908, signal :
날짜 : 2001-10-31 00:00:00, 모멘텀 인덱스 : -0.20715647654510194, signal :
날짜 : 2001-11-30 00:00:00, 모멘텀 인덱스 : 0.06424249585699449, signal : buy
날짜 : 2001-12-31 00:00:00, 모멘텀 인덱스 : 0.43193296812032056, signal : buy
날짜 : 2002-01-31 00:00:00, 모멘텀 인덱스 : 0.012716974885304877, signal : buy
날짜 : 2002-02-28 00:00:00, 모멘텀 인덱스 : 0.3545210627987174, signal : buy
날짜 : 2002-03-28 00:00:00, 모멘텀 인덱스 : -0.016764699706081965, signal :
날짜 : 2002-04-30 00:00:00, 모멘텀 인덱스 : -0.0714006717245591, signal :
날짜 : 2002-05-31 00:00:00, 모멘텀 인덱스 : 0.2165408197433074, signal : buy
날짜 : 2002-06-28 00:00:00, 모멘텀 인덱스 : 0.002150760842817734, signal : buy
날짜 : 2002-07-31 00:00:00, 모멘텀 인덱스 : -0.05694548868983018, signal :
날짜 : 2002-08-30 00:00:00, 모멘텀 인덱스 : -0.17735856208846257, signal :
날짜 : 2002-09-30 00:00:00, 모멘텀 인덱스 : -0.04900078824129461, signal :
날짜 : 2002-10-31 00:00:00, 모멘텀 인덱스 : -0.1742597090802528, signal :
날짜 : 2002-11-29 00:00:00, 모멘텀 인덱스 : -0.2455402696246144, signal :
날짜 : 2002-12-31 00:00:00, 모멘텀 인덱스 : -0.29223780612393824, signal :
날짜 : 2003-01-31 00:00:00, 모멘텀 인덱스 : -0.4203076382015456, signal :
날짜 : 2003-02-28 00:00:00, 모멘텀 인덱스 : -0.33824847460498064, signal :
날짜 : 2003-03-31 00:00:00, 모멘텀 인덱스 : -0.3658642306640605, signal :
날짜 : 2003-04-30 00:00:00, 모멘텀 인덱스 : -0.41738797188835675, signal :
날짜 : 2003-05-30 00:00:00, 모멘텀 인덱스 : -0.3896998757855995, signal :
날짜 : 2003-06-30 00:00:00, 모멘텀 인덱스 : 0.012979774567506208, signal : buy
날짜 : 2003-07-31 00:00:00, 모멘텀 인덱스 : 0.24901662212317444, signal : buy
날짜 : 2003-08-29 00:00:00, 모멘텀 인덱스 : 0.42915232420941773, signal : buy
날짜 : 2003-09-30 00:00:00, 모멘텀 인덱스 : 0.5593100970334481, signal : buy
날짜 : 2003-10-31 00:00:00, 모멘텀 인덱스 : 0.28935931962019046, signal : buy
날짜 : 2003-11-28 00:00:00, 모멘텀 인덱스 : 0.4767741463198365, signal : buy
날짜 : 2003-12-31 00:00:00, 모멘텀 인덱스 : 0.4591770959028769, signal : buy
날짜 : 2004-01-30 00:00:00, 모멘텀 인덱스 : 0.48816100499022874, signal : buy
날짜 : 2004-02-27 00:00:00, 모멘텀 인덱스 : 0.5029982070381209, signal : buy
날짜 : 2004-03-31 00:00:00, 모멘텀 인덱스 : 0.6916552986079167, signal : buy
날짜 : 2004-04-30 00:00:00, 모멘텀 인덱스 : 0.9015481093959845, signal : buy
날짜 : 2004-05-28 00:00:00, 모멘텀 인덱스 : 0.4362122660911649, signal : buy
날짜 : 2004-06-30 00:00:00, 모멘텀 인덱스 : 0.4721934581029994, signal : buy
날짜 : 2004-07-30 00:00:00, 모멘텀 인덱스 : 0.5436439434774598, signal : buy
날짜 : 2004-08-31 00:00:00, 모멘텀 인덱스 : 0.4303403975298048, signal : buy
날짜 : 2004-09-30 00:00:00, 모멘텀 인덱스 : 0.6645751752957718, signal : buy
날짜 : 2004-10-29 00:00:00, 모멘텀 인덱스 : 0.6928793896839156, signal : buy
날짜 : 2004-11-30 00:00:00, 모멘텀 인덱스 : 1.5059782392701995, signal : buy
날짜 : 2004-12-31 00:00:00, 모멘텀 인덱스 : 2.137575194661067, signal : buy
날짜 : 2005-01-31 00:00:00, 모멘텀 인덱스 : 1.8546106776570532, signal : buy
날짜 : 2005-02-28 00:00:00, 모멘텀 인덱스 : 2.214883100674925, signal : buy
날짜 : 2005-03-31 00:00:00, 모멘텀 인덱스 : 2.3180465818906515, signal : buy
날짜 : 2005-04-29 00:00:00, 모멘텀 인덱스 : 2.232737912586903, signal : buy
날짜 : 2005-05-31 00:00:00, 모멘텀 인덱스 : 1.5702059387873306, signal : buy
날짜 : 2005-06-30 00:00:00, 모멘텀 인덱스 : 1.4437612897332306, signal : buy
날짜 : 2005-07-29 00:00:00, 모멘텀 인덱스 : 1.2764378020257685, signal : buy
날짜 : 2005-08-31 00:00:00, 모멘텀 인덱스 : 1.4731808577677277, signal : buy

In [94]:
# 모멘텀 인덱스가 1보다 작을 때는 전년도의 값보다 전월의 값이 작을 때
df['trade'].value_counts()

trade
buy    6092
       3623
Name: count, dtype: int64

In [95]:
df.loc[datetime(2010,1,1) : datetime.now(), ['Adj Close', 'trade']].tail(30)

             Adj Close trade
Date
2019-05-13  185.720001   buy
2019-05-14  188.660004   buy
2019-05-15  190.919998   buy
2019-05-16  190.080002   buy
2019-05-17  189.000000   buy
2019-05-20  183.089996   buy
2019-05-21  186.600006   buy
2019-05-22  182.779999   buy
2019-05-23  179.660004   buy
2019-05-24  178.970001   buy
2019-05-28  178.229996   buy
2019-05-29  177.380005   buy
2019-05-30  178.300003   buy
2019-05-31  175.070007   buy
2019-06-03  173.300003   buy
2019-06-04  179.639999   buy
2019-06-05  182.539993   buy
2019-06-06  185.220001   buy
2019-06-07  190.149994   buy
2019-06-10  192.580002   buy
2019-06-11  194.809998   buy
2019-06-12  194.190002   buy
2019-06-13  194.149994   buy
2019-06-14  192.740005   buy
2019-06-17  193.889999   buy
2019-06-18  198.449997   buy
2019-06-19  197.869995   buy
2019-06-20  199.460007   buy
2019-06-21  198.779999   buy
2019-06-24  199.169998

In [96]:
flag = (df['trade'] == 'buy') & (df.index >= datetime(2008,1,1)) 
df.loc[flag]['Adj Close'].sum()

195054.58020800003

In [97]:
df[~flag]['Adj Close'].sum()

61319.33764799999

In [98]:
# 수익률
df2 = df.copy()
df2['rtn'] = 1
for idx in df2.index:
    # 매수
    if (df2.shift().loc[idx, 'trade'] == '') & (df2.loc[idx,'trade'] == 'buy'):
        buy = df2.loc[idx, 'Adj Close']
        print(f"매수일 : {idx}, 매수가 : {buy}")
    elif (df2.shift().loc[idx, 'trade'] == 'buy') & (df2.loc[idx, 'trade'] == ''):
        sell = df2.loc[idx, 'Adj Close']
        print(f"매도일 : {idx}, 매도가 : {sell}")
        
        rtn = sell / buy
        df2.loc[idx, 'rtn'] = rtn
        print(f"수익률 : {rtn}")
    
df2['acc_rtn'] = df2['rtn'].cumprod()
acc_rtn = df2.iloc[-1,-1]
print(acc_rtn)

매수일 : 1982-09-30 00:00:00, 매수가 : 0.260594
매도일 : 1982-10-29 00:00:00, 매도가 : 0.362333
수익률 : 1.390411905109097
매수일 : 1982-11-30 00:00:00, 매수가 : 0.455147

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_17528\4048752773.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.390411905109097' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, 'rtn'] = rtn

매도일 : 1983-10-31 00:00:00, 매도가 : 0.323065
수익률 : 0.7098036458550754
매수일 : 1984-09-28 00:00:00, 매수가 : 0.358763
매도일 : 1985-03-29 00:00:00, 매도가 : 0.315926
수익률 : 0.8805980549833734
매수일 : 1986-03-31 00:00:00, 매수가 : 0.403385
매도일 : 1988-08-31 00:00:00, 매도가 : 1.151157
수익률 : 2.8537427023811
매수일 : 1988-10-31 00:00:00, 매수가 : 1.115071
매도일 : 1988-12-30 00:00:00, 매도가 : 1.165048
수익률 : 1.0448195675432328
매수일 : 1989-06-30 00:00:00, 매수가 : 1.199905
매도일 : 1989-07-31 00:00:00, 매도가 : 1.156272
수익률 : 0.9636362878727899
매수일 : 1989-08-31 00:00:00, 매수가 : 1.297513
매도일 : 1990-01-31 00:00:00, 매도가 : 0.993802
수익률 : 0.7659283567871767
매수일 : 1990-04-30 00:00:00, 매수가 : 1.15462
매도일 : 1990-05-31 00:00:00, 매도가 : 1.21296
수익률 : 1.0505274462593754
매수일 : 1990-06-29 00:00:00, 매수가 : 1.315878
매도일 : 1990-08-31 00:00:00, 매도가 : 1.091278
수익률 : 0.8293154836542597
매수일 : 1990-12-31 00:00:00, 매수가 : 1.272488
매도일 : 1991-07-31 00:00:00, 매도가 : 1.375062
수익률 : 1.0806090116370448
매수일 : 1991-08-30 00:00:00, 매수가 : 1.57931
매도일 : 1992-08-31 00:00:00, 매도가 : 1.383083
수익률 : 0.8757514357535886
매수일 : 1992-11-30 00:00:00, 매수가 : 1.732536
매도일 : 1993-01-29 00:00:00, 매도가 : 1.792798
수익률 : 1.0347825384292157
매수일 : 1993-06-30 00:00:00, 매수가 : 1.195273
매도일 : 1993-07-30 00:00:00, 매도가 : 0.839717
수익률 : 0.7025315555525808
매수일 : 1994-08-31 00:00:00, 매수가 : 1.116031
매도일 : 1995-10-31 00:00:00, 매도가 : 1.132567
수익률 : 1.0148167927234997
매수일 : 1998-02-27 00:00:00, 매수가 : 0.739149
매도일 : 2000-10-31 00:00:00, 매도가 : 1.224094
수익률 : 1.6560855794975033
매수일 : 2001-11-30 00:00:00, 매수가 : 1.332816
매도일 : 2002-03-28 00:00:00, 매도가 : 1.481115
수익률 : 1.1112674217596428
매수일 : 2002-05-31 00:00:00, 매수가 : 1.457963
매도일 : 2002-07-31 00:00:00, 매도가 : 0.954872
수익률 : 0.6549356876683429
매수일 : 2003-06-30 00:00:00, 매수가 : 1.192651
매도일 : 2008-10-31 00:00:00, 매도가 : 13.464565
수익률 : 11.289610288340848
매수일 : 2009-09-30 00:00:00, 매수가 : 23.195999
매도일 : 2013-02-28 00:00:00, 매도가 : 56.055256
수익률 : 2.41659158547127
매수일 : 2013-12-31 00:00:00, 매수가 : 72.612869
매도일 : 2016-01-29 00:00:00, 매도가 : 91.581261
수익률 : 1.2612263123772178
매수일 : 2016-12-30 00:00:00, 매수가 : 111.392426
매도일 : 2019-01-31 00:00:00, 매도가 : 165.093445
수익률 : 1.4820886026847104
매수일 : 2019-03-29 00:00:00, 매수가 : 189.221313
매도일 : 2019-06-24 00:00:00, 매도가 : 199.169998
수익률 : 1.052576979000246
75.26608134071219

In [99]:
df2.tail(30)

,Open,High,Low,Close,Adj Close,Volume,STD-YM,trade,rtn,acc_rtn
Date,,,,,,,,,,
2019-05-13,187.710007,189.479996,182.850006,185.720001,185.720001,57430600.0,2019-05,buy,1.000000,71.506486
2019-05-14,186.410004,189.699997,185.410004,188.660004,188.660004,36529700.0,2019-05,buy,1.000000,71.506486
2019-05-15,186.270004,191.750000,186.020004,190.919998,190.919998,26544700.0,2019-05,buy,1.000000,71.506486
2019-05-16,189.910004,192.470001,188.839996,190.080002,190.080002,33031400.0,2019-05,buy,1.000000,71.506486
2019-05-17,186.929993,190.899994,186.759995,189.000000,189.000000,32879100.0,2019-05,buy,1.000000,71.506486
2019-05-20,183.520004,184.350006,180.279999,183.089996,183.089996,38612300.0,2019-05,buy,1.000000,71.506486
2019-05-21,185.220001,188.000000,184.699997,186.600006,186.600006,28364800.0,2019-05,buy,1.000000,71.506486
2019-05-22,184.660004,185.710007,182.550003,182.779999,182.779999,29748600.0,2019-05,buy,1.000000,71.506486
2019-05-23,179.800003,180.539993,177.809998,179.660004,179.660004,36529700.0,2019-05,buy,1.000000,71.506486
2019-05-24,180.199997,182.139999,178.619995,178.970001,178.970001,23714700.0,2019-05,buy,1.000000,71.506486
2019-05-28,178.919998,180.589996,177.910004,178.229996,178.229996,27948200.0,2019-05,buy,1.000000,71.506486
2019-05-29,176.419998,179.350006,176.000000,177.380005,177.380005,28481200.0,2019-05,buy,1.000000,71.506486
2019-05-30,177.949997,179.229996,176.669998,178.300003,178.300003,21218400.0,2019-05,buy,1.000000,71.506486
2019-05-31,176.229996,177.990005,174.990005,175.070007,175.070007,27043600.0,2019-05,buy,1.000000,71.506486
2019-06-03,175.600006,177.919998,170.270004,173.300003,173.300003,40396100.0,2019-06,buy,1.000000,71.506486
2019-06-04,175.440002,179.830002,174.520004,179.639999,179.639999,30968000.0,2019-06,buy,1.000000,71.506486
2019-06-05,184.279999,184.990005,181.139999,182.539993,182.539993,29773400.0,2019-06,buy,1.000000,71.506486
2019-06-06,183.080002,185.470001,182.149994,185.220001,185.220001,22526300.0,2019-06,buy,1.000000,71.506486
2019-06-07,186.509995,191.919998,185.770004,190.149994,190.149994,30684400.0,2019-06,buy,1.000000,71.506486
2019-06-10,191.809998,195.369995,191.619995,192.580002,192.580002,26220900.0,2019-06,buy,1.000000,71.506486
2019-06-11,194.860001,196.000000,193.600006,194.809998,194.809998,26932900.0,2019-06,buy,1.000000,71.506486
2019-06-12,193.949997,195.970001,193.389999,194.190002,194.190002,18253200.0,2019-06,buy,1.000000,71.506486
2019-06-13,194.699997,196.789993,193.600006,194.149994,194.149994,21674600.0,2019-06,buy,1.000000,71.506486
2019-06-14,191.550003,193.589996,190.300003,192.740005,192.740005,18761500.0,2019-06,buy,1.000000,71.506486
2019-06-17,192.899994,194.960007,192.169998,193.889999,193.889999,14669100.0,2019-06,buy,1.000000,71.506486
2019-06-18,196.050003,200.289993,195.210007,198.449997,198.449997,26551000.0,2019-06,buy,1.000000,71.506486
2019-06-19,199.679993,199.880005,197.309998,197.869995,197.869995,21124200.0,2019-06,buy,1.000000,71.506486
2019-06-20,200.369995,200.610001,198.029999,199.460007,199.460007,21514000.0,2019-06,buy,1.000000,71.506486
2019-06-21,198.800003,200.850006,198.149994,198.779999,198.779999,47735300.0,2019-06,buy,1.000000,71.506486
2019-06-24,198.539993,200.160004,198.169998,199.169998,199.169998,9025362.0,2019-06,,1.052577,75.266081

### 절대 모멘텀 함수
1. create_ym 함수
    - 매개변수 2개
        - _df
        - _col = 'Adj Close'
    - 데이터프레임의 복사본을 생성해서 작업
    - 컬럼에 Date가 존재하는가? 존재한다면 Date를 인데스로 변환
    - Index를 시계열 데이터로 변경
    - 데이터 중 결측치나 양의 무한대, 음의 무한대를 제외
    - 기준이 되는 컬럼을 제외하고 모두 삭제
    - 'STD-YM' 파생변수를 생성하여 index에서 년-월을 추출하여 대입
    - 위에서 작업된 데이터프레임을 되돌려준다


2. 거래내역 trade 생성 함수
    - 매개변수
        - _df (이전 데이터프레임)
        - _start = '2010-01-01'
        - _end = datetime.now()
        - _momentum = 1
        - _select = 1 (기준시점)

3. 세번째 함수
    - 매개변수
        - trade 컬럼이 추가될 데이터프레임(_df1)
        - 월말/월초의 데이터프레임(_df2)
        - 모멘텀 스코어(_score = 1)

    - _df1의 복사본을 생성
    - result에 trade = ''
    - 반복문을 이용하여 구매내역 추가
    - 구매내역이 추가된 데이터프레임을 되돌려준다

In [100]:
# STD-YM 컬럼 만들기

def create_ym(
    _df,
    _col = 'Adj Close'
):
    result = _df.copy()
    if 'Date' in result.columns:
        result.set_index('Date', inplace=True)
        
    result.index = pd.to_datetime(result.index, utc = False)
    
    flag = result.isin([np.nan, np.inf, -np.inf]).any(axis=1)
    result = result.loc[~flag, [_col]]
    
    result = result[[_col]]
    
    result['STD-YM'] = result.index.strftime('%Y-%m')
    
    return result

In [103]:
new_df = pd.read_csv("../../data/csv/AMZN.csv", index_col = "Date")
newnew = create_ym(new_df)

In [102]:
def create_month(
    _df,
    _start = '2010-01-01',
    _end = datetime.now(),
    _momentum = 12,
    _select = 1
):
    
    if _select == 1:
        flag = _df['STD-YM'] != _df['STD-YM'].shift(-1)
    elif _select == 0:
        flag = _df['STD-YM'] != _df['STD-YM'].shift(1)
    else:
        return "_select의 값은 0 또는 1입니다"
    
    result = _df.loc[flag]
    
    col = result.columns[0]
    
    result['BF1'] = result[col].shift(1)
    
    result['BF2'] = result[col].shift(_momentum)
    
    try:
        result.index = result.index.tz_localize(None)
        start = datetime.strptime(_start, '%Y-%m-%d')
    except Exception as e:
        print(e)
    
    
    result = result.loc[start:_end]
    return result

In [104]:
create_month(newnew)

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_17528\736641197.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['BF1'] = result[col].shift(1)
C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_17528\736641197.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['BF2'] = result[col].shift(_momentum)

              Adj Close   STD-YM          BF1          BF2
Date
2010-01-29   125.410004  2010-01   134.520004    58.820000
2010-02-26   118.400002  2010-02   125.410004    64.790001
2010-03-31   135.770004  2010-03   118.400002    73.440002
2010-04-30   137.100006  2010-04   135.770004    80.519997
2010-05-28   125.459999  2010-05   137.100006    77.989998
...                 ...      ...          ...          ...
2019-02-28  1639.829956  2019-02  1718.729980  1512.449951
2019-03-29  1780.750000  2019-03  1639.829956  1447.339966
2019-04-30  1926.520020  2019-04  1780.750000  1566.130005
2019-05-31  1775.069946  2019-05  1926.520020  1629.619995
2019-06-24  1907.953857  2019-06  1775.069946  1699.800049

[114 rows x 4 columns]

In [105]:
import warnings
warnings.filterwarnings('ignore')

In [112]:
month_last_df = create_month(newnew)

In [111]:
df10 = create_month(newnew, _momentum=6)
df10.head(15)

             Adj Close   STD-YM         BF1         BF2
Date
2010-01-29  125.410004  2010-01  134.520004   85.760002
2010-02-26  118.400002  2010-02  125.410004   81.190002
2010-03-31  135.770004  2010-03  118.400002   93.360001
2010-04-30  137.100006  2010-04  135.770004  118.809998
2010-05-28  125.459999  2010-05  137.100006  135.910004
2010-06-30  109.260002  2010-06  125.459999  134.520004
2010-07-30  117.889999  2010-07  109.260002  125.410004
2010-08-31  124.830002  2010-08  117.889999  118.400002
2010-09-30  157.059998  2010-09  124.830002  135.770004
2010-10-29  165.229996  2010-10  157.059998  137.100006
2010-11-30  175.399994  2010-11  165.229996  125.459999
2010-12-31  180.000000  2010-12  175.399994  109.260002
2011-01-31  169.639999  2011-01  180.000000  117.889999
2011-02-28  173.289993  2011-02  169.639999  124.830002
2011-03-31  180.130005  2011-03  173.289993  157.059998

In [ ]:
def create_momentum(
    _df1,
    _df2,
    _score = 1
):
    result = _df1.copy()